library(testthat)
source(file.path(x,"R_Repo","R/fars_function.R"))
setwd()
x <-fars_read("data/accident_2013.csv.bz2")
test_that("make_filename",expect_equal(make_filename(2015),"accident_2015.csv.bz2"))
